# Generated by Django 4.1.2 on 2023-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_furigana_fname_user_furigana_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='furigana_fname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='furigana_lname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
