# Generated by Django 4.1.2 on 2023-03-08 07:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_furigana_fname_alter_user_furigana_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_directory_path),
        ),
    ]
