# Generated by Django 4.1.2 on 2023-03-23 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_division_divisionmember_remove_groupmember_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisionmember',
            options={'permissions': [('rest_list', 'Can list on rest api')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('rest_list', 'Can list on rest api')]},
        ),
        migrations.AlterField(
            model_name='division',
            name='members',
            field=models.ManyToManyField(related_name='division_set', through='users.DivisionMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
