# Generated by Django 4.1.2 on 2023-03-24 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_divisionmember_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'permissions': [('rest_list', 'Can list on rest api')], 'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
    ]
