image: "python:3.10"

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: project_ci_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip  
  - pip install pipenv
  - pipenv install

stages:
  - Python Lint
  - Django Tests

flake8:
  stage: Python Lint
  script:
    - pipenv run flake8

test:
  stage: Django Tests
  script:
    # Runs tests everytime a commit is created to check that all test is passing
    - pipenv run python manage.py test
