image: "python:3.10"

before_script:
  - apt-get -qq update && apt-get -qq install -y python
  - apt-get -qq update
  - apt-get -qq install -y python python-virtualenv python-pip
  - virtualenv venv
  - . venv/bin/activate
  - pip install -r requirements.txt

stages:
  - Python Lint
  - Django Tests

flake8:
  stage: Python Lint
  script:
    - flake8

test:
  stage: Django Tests
  script:
    # this configures Django application to use attached postgres database that is run on `postgres` host
    - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
    # Runs tests everytime a commit is created to check that all test is passing
    - python manage.py test
