stages:
  - Build
  - Python Lint
  - Django Tests

myJob:
  stage: Build
  image: python:3.10
  script:
    - apt-get update -q -y
    - apt-get install -y python-pip
    - python -V
    - echo "hello world"
    - pip install -r requirements.txt
  artifacts:
    untracked: true

myJob2:
  stage: Python Lint
  image: python:3.10
  script:
    - flake8

myJob3:
  stage: Django Tests
  image: python:3.10
  script:
    # this configures Django application to use attached postgres database that is run on `postgres` host
    - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
    # Runs tests everytime a commit is created to check that all test is passing
    - python manage.py test
